[package]
name = "abwab"
edition = "2024"
author = "doomed-neko"

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
tao = "0.30.8"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
url = "2.5.4"
wry = "0.47.2"
