[package]
name = "abwab"
edition = "2021"
author = "doomed-neko"
version = "1.0.0"

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
url = "2.5.4"
